from platform import system

Import("env")

sources = []
sources += env.Glob("nova/driver/*.cpp")
sources += env.Glob("nova/input/*.cpp")
sources += env.Glob("nova/loading/*.cpp")

sources += env.Glob("nova/modules/*.cpp")
sources += env.Glob("nova/modules/builtins/*.cpp")

env.appendSourcePath("#TermUtils/include/")
env.appendSourcePath("#src/")
env.appendSourcePath("#include/")

if not env.isMSVC():
    env.Append(LINKFLAGS=["-rdynamic"])

    env.withLibraries("dl")

# This is where shit gets tricky
env.StaticLibrary("novasources", sources)
# This _should_ be global
env.appendLibPath("#" + env.getBinPath())
env.withLibraries(["-Wl,--whole-archive", "-lnovasources", "-Wl,--nowholearchive"], append = False)

Default(env.Program("nova", env.Glob("nova/*.cpp")))
