name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Set up python; requires for SCons and Conan
      - uses: actions/setup-python@v2
      - name: Run hooks
        run: |
          #wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          #echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" | sudo tee -a /etc/apt/sources.list
          sudo apt update
          sudo apt install clang-format-10
          sudo ln -sf /usr/bin/clang-format-10 /usr/bin/clang-format
          python3 -m pip install -r requirements.txt
          pre-commit run --all-files
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    # Contains the build matrix, and yes, it's a bit of a clusterfuck
    strategy:
      fail-fast: false
      matrix:
        # Config: contains the system setup.
        config:
          - g++-10-ubuntu
          - clang++-10-ubuntu
          - clang++-11-macos
          - msvc-bundled-windows

        include:
          # This contains the actual definition of usable stuff for each configuration.
          # This can also include packages in the future, if I can find out
          # how GH Actions "if" works. /shrug
          - config: g++-10-ubuntu
            os: ubuntu-20.04
            compiler: g++-10
            ccompiler: gcc-10
          - config: clang++-10-ubuntu
            os: ubuntu-20.04
            compiler: clang++-10
            ccompiler: clang-10
          - config: clang++-11-macos
            os: macos-latest
            compiler: clang++
            ccompiler: clang
          - config: msvc-bundled-windows
            os: windows-latest
            compiler: cl.exe
            ccompiler: cl.exe
    # The OS to run on
    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    # Set up python; requires for SCons and Conan
    - uses: actions/setup-python@v2
    # Set up ninja so we don't need to make several builds for the CI.
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Set env
      # Both CXX and CC needs to be set
      run: |
        echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV
        echo "CC=${{ matrix.ccompiler }}" >> $GITHUB_ENV
    # Install conan
    - name: Install conan
      run: |
        python -m pip install conan
        conan profile new --detect default
        mkdir build
    - name: Shitdows build
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        cmake .. -GNinja -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_DEST_WIN }}\scripts\buildsystems\vcpkg.cmake
        ninja
    - name: Build
      if: matrix.os != 'windows-latest'
      run: |
        cd build
        cmake .. -GNinja
        ninja
        cd ..
    - name: Build and run test
      run: |
        echo "Not implemented :)"
